import { MedicalRecord } from "../types";

export const calculateBMI = (height: string, weight: string): string => {
  if (!height || !weight) return "";

  const heightInMeters = parseFloat(height) / 100; // Convert cm to meters
  const weightInKg = parseFloat(weight);

  if (
    isNaN(heightInMeters) ||
    isNaN(weightInKg) ||
    heightInMeters <= 0 ||
    weightInKg <= 0
  ) {
    return "";
  }

  const bmi = weightInKg / (heightInMeters * heightInMeters);
  return bmi.toFixed(2);
};

export const getEmptyMedicalRecord = (): MedicalRecord => ({
  nombreEmpresa: "",
  fecha: new Date().toISOString().split("T")[0],
  folio: "",
  tipoExamen: "PERIÓDICO",
  nombre: "",
  edad: "",
  sexo: "",
  fechaNacimiento: "",
  direccion: "",
  telefono: "",
  email: "",
  edadInicioLabores: "",
  puestoSolicitado: "",
  nss: "",
  empresa1Nombre: "",
  empresa1Anos: "",
  empresa1Puesto: "",
  empresa1Disolventes: "false",
  empresa1Quimicos: "false",
  empresa1Metales: "false",
  empresa1Polvo: "false",
  empresa1Gases: "false",
  empresa1Ruido: "false",
  empresa1SobreEsfuerzo: "false",
  empresa1Estres: "false",
  empresa1Biologicos: "false",
  empresa1Ergonomicos: "false",
  empresa1Calor: "false",
  empresa1Otro: "false",
  empresa2Nombre: "",
  empresa2Anos: "",
  empresa2Puesto: "",
  empresa2Disolventes: "false",
  empresa2Quimicos: "false",
  empresa2Metales: "false",
  empresa2Polvo: "false",
  empresa2Gases: "false",
  empresa2Ruido: "false",
  empresa2SobreEsfuerzo: "false",
  empresa2Estres: "false",
  empresa2Biologicos: "false",
  empresa2Ergonomicos: "false",
  empresa2Calor: "false",
  empresa2Otro: "false",
  empresa3Nombre: "",
  empresa3Anos: "",
  empresa3Puesto: "",
  empresa3Disolventes: "false",
  empresa3Quimicos: "false",
  empresa3Metales: "false",
  empresa3Polvo: "false",
  empresa3Gases: "false",
  empresa3Ruido: "false",
  empresa3SobreEsfuerzo: "false",
  empresa3Estres: "false",
  empresa3Biologicos: "false",
  empresa3Ergonomicos: "false",
  empresa3Calor: "false",
  empresa3Otro: "false",
  diabetes: "false",
  hipertension: "false",
  ulceras: "false",
  obesidad: "false",
  epilepsia: "false",
  nefropatias: "false",
  tuberculosis: "false",
  alergias: "false",
  dislipidemias: "false",
  artitis: "false",
  oncologicos: "false",
  neumopatias: "false",
  artritis: "false",
  cardiopatias: "false",
  otros: "false",
  quien: "",
  patDiabetes: "false",
  patHipertension: "false",
  patLunbargias: "false",
  patOftalmo: "false",
  patEpilepsia: "false",
  patEpoc: "false",
  patQuirurgico: "false",
  patCirugias: "false",
  patNefropatias: "false",
  patTuberculosis: "false",
  patAlergias: "false",
  patDislipidemias: "false",
  patArtitis: "false",
  patAnsiedad: "false",
  patPsiquiatricos: "false",
  patTransfusiones: "false",
  patOncologicos: "false",
  patTraumaticos: "false",
  patEts: "false",
  patCardiopatias: "false",
  patNeoplasias: "false",
  patDepresion: "false",
  patAccidentes: "false",
  patControl: "",
  viviendaMaterial: "",
  viviendaHabitaciones: "",
  viviendaPersonas: "",
  viviendaAguaPotable: "false",
  viviendaElectricidad: "false",
  viviendaDrenaje: "false",
  viviendaPavimento: "false",
  habitosDiario: "false",
  habitosCambioRopa: "false",
  habitosCepilloDientes: "false",
  habitosOtro: "false",
  alimentacionCarnesRojas: "false",
  alimentacionPollo: "false",
  alimentacionPescado: "false",
  alimentacionVerduras: "false",
  alimentacionFrutas: "false",
  alimentacionLegumbres: "false",
  alimentacionLacteos: "false",
  alimentacionHuevos: "false",
  alimentacionBebidasAzucaradas: "false",
  alimentacionChatarra: "false",
  alimentacionAgua: "false",
  alimentacionOtras: "false",
  alcoholConsumo: "false",
  alcoholFrecuencia: "",
  alcoholCantidad: "",
  alcoholAnos: "",
  alcoholAnosInactivo: "",
  tabacoConsumo: "false",
  tabacoFrecuencia: "",
  tabacoCantidad: "",
  tabacoAnos: "",
  tabacoAnosInactivo: "",
  drogasConsumo: "false",
  drogasObservaciones: "",
  incapacitadoRiesgoTrabajo: "false",
  incapacitadoRiesgoTrabajoValuacion: "",
  incapacitadoEnfermedad: "false",
  incapacitadoEnfermedadValuacion: "",
  padeceEnfermedad: "false",
  padeceEnfermedadValuacion: "",
  habitosAlimenticios: "",
  actividadFisica: "",
  tabaquismo: "",
  alcoholismo: "",
  drogadiccion: "",
  vacunacion: "",
  talla: "",
  peso: "",
  imc: "",
  tensionArterial: "",
  frecuenciaCardiaca: "",
  frecuenciaRespiratoria: "",
  temperatura: "",
  cabeza: "",
  cuello: "",
  torax: "",
  abdomen: "",
  extremidades: "",
  columnaVertebral: "",
  piel: "",
  neurologico: "",

  // Campos detallados de exploración
  // Cráneo
  craneotamano: "false",
  craneopelo: "false",
  craneocara: "false",
  craneoObservaciones: "",

  // Nariz
  nariztabique: "false",
  narizmucosas: "false",
  narizotro: "false",
  narizObservaciones: "",

  // Ojos
  ojosconjuntivas: "false",
  ojospupilas: "false",
  ojosparpados: "false",
  ojosObservaciones: "",

  // Oídos
  oidospabellon: "false",
  oidosCAE: "false",
  oidostimpanos: "false",
  oidosObservaciones: "",

  // Cuello detallado
  cuellogangios: "false",
  cuellotiroides: "false",
  cuellopulsos: "false",
  cuelloObservaciones: "",

  // Abdomen detallado
  abdomenmegalias: "false",
  abdomenhernia: "false",
  abdomenotros: "false",
  abdomenObservaciones: "",

  // Boca
  bocamucosas: "false",
  bocadentadura: "false",
  bocalengua: "false",
  bocaencias: "false",
  bocalaringe: "false",
  bocaamigdalas: "false",
  bocaObservaciones: "",

  // Tórax
  toraxforma: "false",
  toraxRCardiaco: "false",
  toraxCamposPul: "false",
  toraxmamas: "false",
  toraxObservaciones: "",

  // Genitales
  genitalesfimosis: "false",
  genitalesvarico: "false",
  genitaleshernia: "false",
  genitalesotros: "false",
  genitalesObservaciones: "",

  // Agudeza visual
  agudezaVisualOD: "",
  agudezaVisualOI: "",
  agudezaVisualIZQ: "false",
  agudezaVisualDER: "false",

  // Miembros
  // Torácicos
  miembrosToraxIntegridad: "false",
  miembrosToraxForma: "false",
  miembrosToraxArticulaciones: "false",
  miembrosToraxTonoMuscular: "false",
  miembrosToraxReflejos: "false",
  miembrosToraxSensibilidad: "false",

  // Pélvicos
  miembrosPelvicosIntegridad: "false",
  miembrosPelvicosForma: "false",
  miembrosPelvicosArticulaciones: "false",
  miembrosPelvicosTonoMuscular: "false",
  miembrosPelvicosReflejos: "false",
  miembrosPelvicosSensibilidad: "false",

  // Inferiores
  miembrosInferioresIntegridad: "false",
  miembrosInferioresForma: "false",
  miembrosInferioresArticulaciones: "false",
  miembrosInferioresTonoMuscular: "false",
  miembrosInferioresReflejos: "false",
  miembrosInferioresSensibilidad: "false",

  // Superiores
  miembrosSuperioresIntegridad: "false",
  miembrosSuperioresForma: "false",
  miembrosSuperioresArticulaciones: "false",
  miembrosSuperiorestonoMuscular: "false",
  miembrosSuperioresReflejos: "false",
  miembrosSuperioresSensibilidad: "false",

  diagnosticos: "",
  observaciones: "",
  recomendaciones: "",
  aptitud: "APTO",
  nombreMedico: "",
  cedulaProfesional: "",
  bloodHemoglobin: "",
  quickSedimentation: "",
  urine: "",
  audiometry: "",
  spirometry: "",
  chestXRay: "",
  alcoholemia: "",
  antidoping: "",
  lumbarXRay: "",
  rombergTest: "",
  rombergTestObservations: "",
  especialidadMedico: "",
  babinskiTest: "",
});

export const formSteps = [
  {
    id: "general",
    title: "Información General",
    description: "Datos básicos de la empresa y el examen",
    icon: "Building2",
  },
  {
    id: "personal",
    title: "Datos Personales",
    description: "Información personal del paciente",
    icon: "User",
  },
  {
    id: "laboral",
    title: "Información Laboral",
    description: "Historial y situación laboral",
    icon: "Briefcase",
  },
  {
    id: "antecedentes-familiares",
    title: "Antecedentes Familiares",
    description: "Historial médico familiar",
    icon: "UsersRound",
  },
  {
    id: "antecedentes-personales",
    title: "Antecedentes Personales",
    description: "Historial médico personal",
    icon: "FileHistory",
  },
  {
    id: "habitos",
    title: "Hábitos",
    description: "Estilo de vida y hábitos",
    icon: "Activity",
  },
  {
    id: "exploracion-fisica",
    title: "Exploración Física",
    description: "Signos vitales y mediciones",
    icon: "Stethoscope",
  },
  {
    id: "exploracion-sistemas",
    title: "Exploración por Sistemas",
    description: "Evaluación por sistemas corporales",
    icon: "HeartPulse",
  },
  {
    id: "evaluacion-medica",
    title: "Evaluación Médica",
    description: "Diagnóstico y recomendaciones",
    icon: "ClipboardCheck",
  },
  {
    id: "review",
    title: "Revisión",
    description: "Revisar y generar PDF",
    icon: "FileCheck",
  },
];
